# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "knative.dev/pkg/codegen/cmd/injection-gen",
  "knative.dev/caching/pkg/apis/caching/v1alpha1",
  "knative.dev/test-infra/scripts",
  "knative.dev/test-infra/tools/dep-collector",
  "k8s.io/apimachinery/pkg/util/sets/types",
]

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "743ec37842bffe49dd4221d9026f30fb1d5adbc4"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.16.4"

[[constraint]]
  name = "istio.io/api"
  version = "1.4.1"

[[constraint]]
  name = "istio.io/client-go"
  version = "1.4.1"

[[constraint]]
  name = "github.com/manifestival/manifestival"
  version = "0.5.0"

[[override]]
  name = "knative.dev/pkg"
  branch = "release-0.14"

[[override]]
  name = "knative.dev/test-infra"
  branch = "master"

[[override]]
  name = "knative.dev/eventing"
  branch = "release-0.14"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "k8s.io/gengo"
  non-go = false

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false

[[prune.project]]
  name = "knative.dev/pkg"
  non-go = false
  unused-packages = false

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false
